config/routes.rb
Rails.application.routes.draw do
  #devise_for :players
  devise_for :players, :controllers => { :registrations => 'players/registrations',:sessions => 'players/sessions' }
  
	root 'homes#index'
  resources :games
  resources :players
  resources :leader_boards, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  #validates :title,:start_date,:end_date, presence: true
  has_many :game_players, dependent: :destroy
  has_many :winner_boards, dependent: :destroy
  accepts_nested_attributes_for :game_players, reject_if: :all_blank, allow_destroy: true
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :find_game, only: %i[edit update show destroy]

  # GET /games
  def index
    @games = Game.all
  end

  # GET /games/1
  def show
    @game = Game.find(params[:id])
    @game.delete
    redirect_to games_url, notice: 'game was successfully destroyed.'
  end

  # GET /games/new
  def new
    @game = Game.new
    2.times do
      @game.game_players.build
    end
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  def create
    @game = Game.new(game_params)
    if @game.save
      game_player = find_winner(@game.game_players)
      game_player.update(is_winner: true)
      redirect_to games_path
    else
      render :new
    end
  end

  # PATCH/PUT /games/1
  def update
    if @game.update(game_params)
      redirect_to games_path
    else
      render :edit
    end
  end

  # DELETE /games/1
  def destroy
    @game = Game.find(params[:id])
    @game.delete
    redirect_to games_url, notice: 'game was successfully destroyed.'
  end

  def find_winner(players)
    max_score = players.maximum(:score)
    players.where(score: max_score)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def find_game
    @game = Game.find(params[:id]) rescue current_game
  end

  # Only allow a trusted parameter "white list" through.
  def game_params
    params.require(:game).permit(:title, :start_date, :end_date, game_players_attributes:[:id, :player_id, :game_id, :score])
  end
end

app/views/games/_form.html.erb
<%= link_to 'Back', games_path, class: "btn btn-warning change-employee-role",style: "width:4%;margin-left:95%;margin-top:1%"%>
<div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><%= @game.new_record? ? 'New ' : 'Update '%> Game</h4>
        <form class="form">
          <div class="form-group mb-3 row">
            <%= f.label "Title", class: "col-2 col-form-label" %>
            <div class="col-3">
              <%= f.text_field :title, class: "form-control" %>
            </div>
          </div>

          <div class="form-group mb-3 row">
            <%= f.label "Start Date", class: "col-2 col-form-label" %>
            <div class="col-3">
              <%= f.date_field :start_date, class: "form-control" %>
            </div>
          </div>

          <div class="form-group mb-3 row">
            <%= f.label "End Date", class: "col-2 col-form-label" %>
            <div class="col-3">
              <%= f.date_field :end_date, class: "form-control" %>
            </div>
          </div>

          <%= f.fields_for :game_players do |ff| %>
            <br/><hr>
            <div class="form-group mb-3 row">
              <div class="col-md-10">
                <div class="row">
                  <%= ff.label "Player", class: "col-form-label col-sm-2" %>
                  <div class="col-md-8">
                    <%= ff.select :player_id, Player.all.order(:first_name).collect { |player| [ player&.full_name, player&.id ]}, {include_blank: "Select Player"}, {class: " form-control",style:"width:83%"} %>
                  </div>
                </div>
              </div><br/>
              <div class="col-md-10">
                <div class="row">
                  <%= ff.label :Score, class: "col-form-label col-sm-2",style:'margin-right:3%'%>
                  <div class="col-md-8">
                    <%= ff.text_field :score, class: 'form-control'%>
                  </div>
                </div>
              </div><br/>
            </div>
          <% end %>
           
          <div class="form-group row">
            <%= f.submit @game.new_record? ? 'Create' : 'Update', class: 'btn btn-success d-lg-block m-l-15', id: 'vendor_submit'%>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/games/edit.html.erb
<%= render '/players/navbar'%>
<%= form_for @game do |f| %>
  <%= render "form", f: f %>
<% end %>

app/views/games/index.html.erb
<link rel="stylesheet" type="text/css" href="https://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>
<script>
$(function(){
  $("#game_table").dataTable();
})
</script>
<%= render '/players/navbar'%>
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <div class="row">
					<div class="col-8">
            <h4 class="card-title mb-3">Game List</h4>
          </div>
            <%= link_to 'Create Game', new_game_path, class: "btn btn-warning change-employee-role",style: "width:7%;float:left;margin-left:20%" %>
            <%= link_to 'Back', root_path, class: "btn btn-warning change-employee-role",style: "width:4%;margin-left:1%"%>
        </div><br/>
        <div class="table-responsive employees_list">
          <table id="game_table" class="desk-table display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
              <tr>
                <th>Title</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @games&.each do |game| %>
                <tr>
                  <td><%= game&.title %></td>
                  <td><%= game&.start_date&.to_date %></td>
                  <td><%= game&.end_date&.to_date %></td>

                  <td>
                    <%= link_to edit_game_path(game) do %>
                      <i class="fa fa-edit icon-color-size" data-toggle="tooltip" data-placement="top" title="Edit"></i>
                    <% end %>
                    <%= link_to game_path(game), method: :delete do %>
                      <i class="fa fa-trash icon-color-size" data-toggle="tooltip" data-placement="top" title="Delete"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/games/new.html.erb
<%= render '/players/navbar'%>
<%= form_for @game do |f| %>
  <%= render "form", f: f %>
<% end %>