config/routes.rb
Rails.application.routes.draw do
  #devise_for :players
  devise_for :players, :controllers => { :registrations => 'players/registrations',:sessions => 'players/sessions' }
  
	root 'homes#index'
  resources :games
  resources :players
  resources :leader_boards, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/player.rb
class Player < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	has_many :game_players, dependent: :destroy
	has_many :winner_boards, dependent: :destroy
  validates :first_name,:date_of_joining,:contact_details, presence: true
  # return user's full name
  def full_name
    (self.first_name.present? && self.last_name.present?) ? self.first_name + " " + self.last_name : " "
  end
end

app/controllers/players/confirmations_controller.rb
# frozen_string_literal: true

class Players::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/players/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Players::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/players/passwords_controller.rb
# frozen_string_literal: true

class Players::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/players/registrations_controller.rb
# frozen_string_literal: true

class Players::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @player = Player.new
    super
  end

  # POST /resource
  def create
    @player = Player.new(player_params)
     if @player.save
       flash.now[:success] = "Success fully sign-up."
       redirect_to new_player_session_path
     else
       render 'new'
     end
   end

   def player_params
      params.require(:player).permit(:first_name, :last_name, :date_of_joining, :contact_details, :email, :password)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/players/sessions_controller.rb
# frozen_string_literal: true

class Players::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/players/unlocks_controller.rb
# frozen_string_literal: true

class Players::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :find_player, only: %i[edit update show destroy]

  # GET /players
  def index
    @players = Player.all
  end

  # GET /players/1
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to players_path
    else
      render :new
    end
  end

  # PATCH/PUT /players/1
  def update
    if @player.update(player_params)
      redirect_to players_path
    else
      render :edit
    end
  end

  # DELETE /players/1
  def destroy
    @player.destroy
    redirect_to players_url, notice: 'player was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def find_player
    @player = Player.find(params[:id]) rescue current_player
  end

  # Only allow a trusted parameter "white list" through.
  def player_params
    params.require(:player).permit(:first_name, :last_name, :contact_details, :date_of_joining)
  end
end

app/helpers/players_helper.rb
module PlayersHelper
  # find the no of game win
  def find_no_of_winner(player)
    player.where(is_winner: true).count
  end

  # find the no of game loss
  def find_no_of_loss(player)
    player.where(is_winner: false).count
  end

  # find the average score of all the games
  def find_average_score(player)
    player.average(:score).round(2)
  end

  # find the higest score from all the games
  def find_higest_score(player)
    player.maximum(:score)
  end
end

app/views/players/_form.html.erb
<%= link_to 'Back', players_path, class: "btn btn-warning change-employee-role",style: "width:4%;margin-left:95%;margin-top:1%"%>
<div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><%= @player.new_record? ? 'New ' : 'Update '%> Player</h4>
        <form class="form">
          <div class="form-group mb-3 row">
            <%= f.label "First Name", class: "col-2 col-form-label" %>
            <div class="col-10">
              <%= f.text_field :first_name, class: "form-control" %>
            </div>
          </div>

          <div class="form-group mb-3 row">
            <%= f.label "Last Name", class: "col-2 col-form-label" %>
            <div class="col-10">
              <%= f.text_field :last_name, class: "form-control" %>
            </div>
          </div>

          <div class="form-group mb-3 row">
            <%= f.label "Date Of Joining", class: "col-2 col-form-label" %>
            <div class="col-10">
              <%= f.date_field :date_of_joining, class: "form-control" %>
            </div>
          </div>
        

          <div class="form-group mb-3 row">
            <%= f.label "Contact Details", class: "col-2 col-form-label" %>
            <div class="col-10">
              <%= f.text_field :contact_details, class: "form-control" %>
            </div>
          </div>
              
          <div class="form-group row">
            <%= f.submit @player.new_record? ? 'Create' : 'Update', class: 'btn btn-success d-lg-block m-l-15', id: 'vendor_submit'%>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/players/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <span class="navbar-brand mb-0 h1">SCP</span>
      <%= button_to 'Log Out', destroy_player_session_path, method: :delete,class:"btn btn-info"%>
  </div>
</nav>

app/views/players/edit.html.erb
<%= render 'navbar'%>
<%= form_for @player do |f| %>
  <%= render "form", f: f %>
<% end %>

app/views/players/index.html.erb
<link rel="stylesheet" type="text/css" href="https://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>
<script>
$(function(){
  $("#player_table").dataTable();
})
</script>
<%= render 'navbar'%>
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <div class="row">
					<div class="col-8">
            <h4 class="card-title mb-3">Player List</h4>
          </div>
          
            <%#= link_to 'Create Player', new_player_path, class: "btn btn-warning change-employee-role",style: "width:7%;float:left;margin-left:20%" %>
            <%= link_to 'Back', root_path, class: "btn btn-warning change-employee-role",style: "width:4%;margin-left:95%"%>
        </div><br/>
        <div class="table-responsive employees_list">
          <table id="player_table" class="desk-table display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
              <tr>
                <th>Player Name</th>
                <th>Date Of Joining</th>
                <th>Contact Details</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @players&.each do |player| %>
                <tr>
                  <td><%= player.first_name %></td>
                  <td><%= player.date_of_joining.strftime('%d-%m-%Y') %></td>
                  <td><%= player.contact_details %></td>

                  <td>
                    <%= link_to player_path(player) do %>
                      <i class="fa fa-eye icon-color-size" data-toggle="tooltip" data-placement="top" title="Watch"></i>
                    <%end%>
                    <%= link_to edit_player_path(player) do %>
                      <i class="fa fa-edit icon-color-size" data-toggle="tooltip" data-placement="top" title="Edit"></i>
                    <% end %>
                    <%= link_to player_path(player), method: :delete, data: {confirm: 'Are you sure? '} do %>
                      <i class="fa fa-trash icon-color-size" data-toggle="tooltip" data-placement="top" title="Delete"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/players/new.html.erb
<%= render 'navbar'%>
<%= form_for @player do |f| %>
  <%= render "form", f: f %>
<% end %>

app/views/players/show.html.erb
<%= render 'navbar'%>
<p id="notice"><%= notice %></p>
<html>
<body style="background:#60467e">
<%= link_to 'Edit', edit_player_path(@player), class: "btn btn-warning change-employee-role",style: "width:7%;float:left;margin-left:85%" %>
<%= link_to 'Back', players_path,method: :post, class: "btn btn-warning change-employee-role",style: "width:4%;margin-left:1%"%>
  <div>
    <div class="card text-dark bg-light mb-3" style="width: 30%;float:left;margin-left:15%;margin-right: 5%;height:300px;border-radius: 5%;">
      <div class="card-header"><center><h1 style="color:#60467e">Player Information</h1></center></div>
      <div class="card-body" style="color:#60467e">
       <p class="card-text">
          First name &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp:
          <%= @player.first_name %>
        </p>
        <p class="card-text">
          Last name &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp:
          <%= @player.last_name %>
        </p>
        <p class="card-text">
          Contact Details &nbsp&nbsp:
          <%= @player.contact_details %><br><br>
        </p>
      </div>
    </div>

    <div class="card text-dark bg-light mb-3" style="width: 30%; margin-top:8%; height:300px; border-radius: 5%;">
      <div class="card-header"><center><h1 style="color:#60467e">Game details</center></h1></div>
        <div class="card-body" style="color:#60467e">
          <p class="card-text">
            Number of wins &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp: <%= @player.game_players.present? ? find_no_of_winner(@player.game_players) : 0%>
          </p>  

          <p class="card-text">
            Number of losses &nbsp&nbsp&nbsp: <%= @player.game_players.present? ? find_no_of_loss(@player.game_players) : 0%>
          </p>

          <p class="card-text">
            Average score &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp: <%= @player.game_players.present? ? find_average_score(@player.game_players) : 0 %>
          </p>

          <p class="card-text">
            Highest score &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp: <%= @player.game_players.present? ? find_higest_score(@player&.game_players) : 0%>
          </p>
        </div>
      </div>
    </div>
  </div>
</body>
</html>